name: Sync Shared Configurations

on:
  push:
    branches:
      - main # main 브랜치에 푸시가 발생할 때 워크플로 실행
  workflow_dispatch: # 수동으로 워크플로를 실행할 수 있도록 추가 (선택 사항)

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_FOR_SYNC_CONFIGS }} # PAT를 환경 변수로 설정

    strategy:
      # 각 대상 리포지토리에 대해 독립적인 작업을 실행
      matrix:
        repository: # 여기에 동기화할 대상 리포지토리 목록을 나열합니다.
          - auth-bot

    steps:
      - name: Checkout shared-configs repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: my-org/${{ matrix.repository }}
          token: ${{ secrets.PAT_FOR_SYNC_CONFIGS }}
          path: target-repo

      - name: Sync files
        run: |
          cp -r shared_configs_files/* target-repo/
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: Sync shared configurations from shared-configs repository [skip ci]"
          git push origin HEAD:sync-shared-configs-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_FOR_SYNC_CONFIGS }}
          path: target-repo
          commit-message: "chore: Sync shared configurations"
          title: "chore: Sync shared configurations"
          body: "This PR updates shared configuration files from the [shared-configs repository](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}). Please review and merge.\n\n_Generated by GitHub Actions_."
          branch: sync-shared-configs-${{ github.run_id }}
          base: main
          labels: |
            automated pr
            configuration